# Generated by Django 6.0.3 on 2026-03-15 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_category_options_contact_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='created_daye',
            new_name='created_date',
        ),
    ]
